version: "3.9"

services:
  dockge:
    image: louislam/dockge:1.3.5
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/dashboard:/app/data
      - $INFRA_HOME/stacks:$INFRA_HOME/stacks
    environment:
      - DOCKGE_STACKS_DIR=$INFRA_HOME/stacks
