server:
  log_level: info

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 30s
    remote_write:
      - url: http://${PROMETHEUS_HOST}/api/v1/write
  configs:
    - name: default
      scrape_configs:

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: http://${LOKI_HOST}/loki/api/v1/push
      scrape_configs:
        - job_name: log-scrape
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - source_labels: ["__meta_docker_container_name"]
              regex: "/(.*)"
              target_label: "container"

traces:
  configs:
    - name: default
      remote_write:
        - endpoint: ${TEMPO_HOST}
          insecure: true
      receivers:
        otlp:
          protocols:
            grpc:
      batch:
        timeout: 10s
        send_batch_size: 1024
